chromedriver:
  path: "/opt/homebrew/bin/chromedriver"
  wait_time: 10

output:
  file: "downloaded_table.csv"
  save_invalid_data: false # Set to true to save data even if validation fails

swimmer:
  first_name: "Alyssa"
  last_name: "Wang"
  club_name: "Rockwood Swim Club"
  year: "-1" # -1 for all years
